v0.1

diff --git a/checkpcPRO b/checkpcPRO
--- a/checkpcPRO
+++ b/checkpcPRO
@@ -1,55 +1,35 @@
 #!/bin/bash
 
-require 'sys/proctable'
-
-procs = Sys::ProcTable.ps()
-
-print "Do you want to save the log file? (Y/N): "
-save_log = gets.chomp.downcase == 'y'
-
-if save_log
-  log_file_path = File.join(File.expand_path('~/Desktop'), 'processes.log')
-
-  File.open(log_file_path, 'w') do |f|
-    # Write the header of the log file
-    f.write("Process ID\tCommand Line\tMemory Usage (KB)\n")
-    f.write("-------------------------------------------------\n")
-
-    procs.each do |p|
-      f.write("#{p.pid}\t#{p.cmdline}\t#{p.rss}\n")
-    end
-  end
-
-  puts "Log file saved to #{log_file_path}"
+# Create processes.log file and write process information to it
+echo "Listing processes..."
+echo "This process can take up to 2 hours while it checks the whole computer."
+echo -n "Do you want to save the log file? (Y/N): "
+read save_log
+if [ "$save_log" == "Y" ] || [ "$save_log" == "y" ]
+then
+    echo "Saving processes to ~/Desktop/processes.log"
+    ruby -e 'require "sys/proctable"; procs = Sys::ProcTable.ps(); File.open("#{Dir.home}/Desktop/processes.log", "w") { |f| procs.each { |p| f.puts "Process ID: #{p.pid}\nCommand line: #{p.cmdline}\nMemory usage: #{p.rss} KB\n---------------------" } }'
+    echo "Processes saved successfully."
 else
-  puts "Log not saved"
-end
+    echo "Processes not saved."
+fi
 
-puts "Process ID\tCommand Line\tMemory Usage (KB)"
-puts "-------------------------------------------------"
-procs.each do |p|
-  puts "#{p.pid}\t#{p.cmdline}\t#{p.rss}"
-end
+# Run clamscan and save output to file_checked.log
+echo "Running antivirus scan..."
+clamscan -r / > ~/Desktop/file_checked.log 2>&1
 
-cd ~/Desktop
-touch file_checked.log
+if [ $? -eq 0 ]; then
+    echo "Antivirus scan completed successfully."
+else
+    echo "Error running antivirus scan." >> ~/Desktop/file_checked.log
+fi
 
-lynis audit system >> file_checked.log
+# Look for corrupt files and store in corrupted_files.log
+echo "Looking for corrupt files..."
+grep -i "corrupt" ~/Desktop/file_checked.log > ~/Desktop/corrupted_files.log
 
-clamscan -r / >> file_checked.log
-
-chkrootkit >> file_checked.log
-
-rkhunter -c >> file_checked.log
-
-aide --check >> file_checked.log
-
-tripwire --check >> file_checked.log
-
-osqueryi "SELECT * FROM osquery_info;" >> file_checked.log
-
-openvas-check-setup >> file_checked.log
-
-nmap -sV -p 1-65535 localhost >> file_checked.log
-
-snort -c /etc/snort/snort.conf -T >> file_checked.log
+if [ -f ~/Desktop/corrupted_files.log ]; then
+  echo "Corrupt files found and stored in ~/Desktop/corrupted_files.log"
+else
+  echo "No corrupt files found."
+fi
